const folderStructure = {
  clean: [
    "lib/config/routes",
    "lib/config/theme",
    "lib/core/error",
    "lib/core/network",
    "lib/core/usecases",
    "lib/core/util",
    "lib/features/<fl>/data/data_sources",
    "lib/features/<fl>/data/models",
    "lib/features/<fl>/data/repository",
    "lib/features/<fl>/domain/entities",
    "lib/features/<fl>/domain/repository",
    "lib/features/<fl>/domain/usecases",
    "lib/features/<fl>/presentation/pages",
    "lib/features/<fl>/presentation/widgets",
    "lib/features/<fl>/presentation/bloc",
  ],
  mvvm: [
    "lib/models/<fl>",
    "lib/views/screens/<fl>",
    "lib/views/widgets/<fl>",
    "lib/viewmodel/<fl>",
    "lib/services",
    "lib/utils",
  ],
  mvc: [
    "lib/config/routes",
    "lib/config/theme",
    "lib/core/util",
    "lib/models/<fl>",
    "lib/controllers/<fl>",
    "lib/views/<fl>",
  ],
  custom: [
    "lib/config/routes",
    "lib/config/theme",
    "lib/core/error",
    "lib/core/network",
    "lib/core/util",
    "lib/data",
    "lib/models",
    "lib/repositories",
    "lib/entities",
    "lib/usecases",
    "lib/screens",
    "lib/widgets",
    "lib/features/<fl>/",
  ],
};
export default folderStructure;
